In [1]:
import pandas as pd
from pathlib import Path
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

In [2]:
diabetes_df = pd.read_csv(
    Path("diabetes_012_health_indicators_BRFSS2015 (1).csv")
)
diabetes_df.head(20)

,Diabetes_012,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0
1,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0
2,0.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0
3,0.0,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0
4,0.0,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0
5,0.0,1.0,1.0,1.0,25.0,1.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,2.0,0.0,1.0,10.0,6.0,8.0
6,0.0,1.0,0.0,1.0,30.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,3.0,0.0,14.0,0.0,0.0,9.0,6.0,7.0
7,0.0,1.0,1.0,1.0,25.0,1.0,0.0,0.0,1.0,0.0,...,1.0,0.0,3.0,0.0,0.0,1.0,0.0,11.0,4.0,4.0
8,2.0,1.0,1.0,1.0,30.0,1.0,0.0,1.0,0.0,1.0,...,1.0,0.0,5.0,30.0,30.0,1.0,0.0,9.0,5.0,1.0
9,0.0,0.0,0.0,1.0,24.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,2.0,0.0,0.0,0.0,1.0,8.0,4.0,3.0
10,2.0,0.0,0.0,1.0,25.0,1.0,0.0,0.0,1.0,1.0,...,1.0,0.0,3.0,0.0,0.0,0.0,1.0,13.0,6.0,8.0
11,0.0,1.0,1.0,1.0,34.0,1.0,0.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,30.0,1.0,0.0,10.0,5.0,1.0
12,0.0,0.0,0.0,1.0,26.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,3.0,0.0,15.0,0.0,0.0,7.0,5.0,7.0
13,2.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,4.0,0.0,0.0,1.0,0.0,11.0,4.0,6.0
14,0.0,0.0,1.0,1.0,33.0,1.0,1.0,0.0,1.0,0.0,...,1.0,1.0,4.0,30.0,28.0,0.0,0.0,4.0,6.0,2.0
15,0.0,1.0,0.0,1.0,33.0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,2.0,5.0,0.0,0.0,0.0,6.0,6.0,8.0
16,0.0,1.0,1.0,1.0,21.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,3.0,0.0,0.0,0.0,0.0,10.0,4.0,3.0
17,2.0,0.0,0.0,1.0,23.0,1.0,0.0,0.0,1.0,0.0,...,1.0,0.0,2.0,0.0,0.0,0.0,1.0,7.0,5.0,6.0
18,0.0,0.0,0.0,0.0,23.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,2.0,15.0,0.0,0.0,0.0,2.0,6.0,7.0
19,0.0,0.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,2.0,10.0,0.0,0.0,1.0,4.0,6.0,8.0

In [8]:
BMI_df = diabetes_df[['Diabetes_012', 'BMI']]
BMI_df.head(10)

   Diabetes_012   BMI
0           0.0  40.0
1           0.0  25.0
2           0.0  28.0
3           0.0  27.0
4           0.0  24.0
5           0.0  25.0
6           0.0  30.0
7           0.0  25.0
8           2.0  30.0
9           0.0  24.0

In [9]:
BMI_stroke_df = diabetes_df[['Stroke','BMI']]
BMI_stroke_df.head(10)

   Stroke   BMI
0     0.0  40.0
1     0.0  25.0
2     0.0  28.0
3     0.0  27.0
4     0.0  24.0
5     0.0  25.0
6     0.0  30.0
7     0.0  25.0
8     0.0  30.0
9     0.0  24.0

In [10]:
phys_health_df = diabetes_df[['Diabetes_012', 'PhysHlth']]
phys_health_df.head(10)

   Diabetes_012  PhysHlth
0           0.0      15.0
1           0.0       0.0
2           0.0      30.0
3           0.0       0.0
4           0.0       0.0
5           0.0       2.0
6           0.0      14.0
7           0.0       0.0
8           2.0      30.0
9           0.0       0.0